/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Category = IDL.Variant({
  'other' : IDL.Null,
  'chain' : IDL.Null,
  'bangles' : IDL.Null,
  'anklet' : IDL.Null,
  'bracelet' : IDL.Null,
  'jewellerySet' : IDL.Null,
  'chainPendant' : IDL.Null,
  'earrings' : IDL.Null,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'author' : IDL.Text,
  'coverImage' : ExternalBlob,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
  'paymentVerified' : IDL.Null,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'paymentScreenshot' : ExternalBlob,
  'userId' : IDL.Text,
  'createdAt' : IDL.Int,
  'totalAmount' : IDL.Nat,
  'shippingAddress' : IDL.Text,
  'items' : IDL.Vec(CartItem),
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'customerType' : IDL.Variant({
    'both' : IDL.Null,
    'retailer' : IDL.Null,
    'online' : IDL.Null,
  }),
  'inStock' : IDL.Nat,
  'subcategory' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const CustomerType = IDL.Variant({
  'onlineSeller' : IDL.Null,
  'retailer' : IDL.Null,
});
export const CustomerProfile = IDL.Record({
  'customerType' : CustomerType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(ExternalBlob),
        IDL.Variant({
          'both' : IDL.Null,
          'retailer' : IDL.Null,
          'online' : IDL.Null,
        }),
        IDL.Nat,
      ],
      [],
      [],
    ),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBlogPostById' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(CustomerProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProductById' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getProductsByCustomerType' : IDL.Func(
      [
        IDL.Variant({
          'both' : IDL.Null,
          'retailer' : IDL.Null,
          'online' : IDL.Null,
        }),
      ],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CustomerProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Text], []),
  'removeFromCart' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([CustomerProfile], [], []),
  'updateCartItemQuantity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateCustomerType' : IDL.Func([CustomerType], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(ExternalBlob),
        IDL.Variant({
          'both' : IDL.Null,
          'retailer' : IDL.Null,
          'online' : IDL.Null,
        }),
        IDL.Nat,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Category = IDL.Variant({
    'other' : IDL.Null,
    'chain' : IDL.Null,
    'bangles' : IDL.Null,
    'anklet' : IDL.Null,
    'bracelet' : IDL.Null,
    'jewellerySet' : IDL.Null,
    'chainPendant' : IDL.Null,
    'earrings' : IDL.Null,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'author' : IDL.Text,
    'coverImage' : ExternalBlob,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
    'paymentVerified' : IDL.Null,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Text, 'quantity' : IDL.Nat });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'paymentScreenshot' : ExternalBlob,
    'userId' : IDL.Text,
    'createdAt' : IDL.Int,
    'totalAmount' : IDL.Nat,
    'shippingAddress' : IDL.Text,
    'items' : IDL.Vec(CartItem),
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'customerType' : IDL.Variant({
      'both' : IDL.Null,
      'retailer' : IDL.Null,
      'online' : IDL.Null,
    }),
    'inStock' : IDL.Nat,
    'subcategory' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const CustomerType = IDL.Variant({
    'onlineSeller' : IDL.Null,
    'retailer' : IDL.Null,
  });
  const CustomerProfile = IDL.Record({
    'customerType' : CustomerType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(ExternalBlob),
          IDL.Variant({
            'both' : IDL.Null,
            'retailer' : IDL.Null,
            'online' : IDL.Null,
          }),
          IDL.Nat,
        ],
        [],
        [],
      ),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBlogPostById' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(CustomerProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProductById' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByCustomerType' : IDL.Func(
        [
          IDL.Variant({
            'both' : IDL.Null,
            'retailer' : IDL.Null,
            'online' : IDL.Null,
          }),
        ],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CustomerProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Text], []),
    'removeFromCart' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([CustomerProfile], [], []),
    'updateCartItemQuantity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateCustomerType' : IDL.Func([CustomerType], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(ExternalBlob),
          IDL.Variant({
            'both' : IDL.Null,
            'retailer' : IDL.Null,
            'online' : IDL.Null,
          }),
          IDL.Nat,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };