/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : string,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'author' : string,
  'coverImage' : ExternalBlob,
}
export interface CartItem { 'productId' : string, 'quantity' : bigint }
export type Category = { 'other' : null } |
  { 'chain' : null } |
  { 'bangles' : null } |
  { 'anklet' : null } |
  { 'bracelet' : null } |
  { 'jewellerySet' : null } |
  { 'chainPendant' : null } |
  { 'earrings' : null };
export interface CustomerProfile {
  'customerType' : CustomerType,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type CustomerType = { 'onlineSeller' : null } |
  { 'retailer' : null };
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'paymentScreenshot' : ExternalBlob,
  'userId' : string,
  'createdAt' : bigint,
  'totalAmount' : bigint,
  'shippingAddress' : string,
  'items' : Array<CartItem>,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null } |
  { 'paymentVerified' : null };
export interface Product {
  'id' : string,
  'customerType' : { 'both' : null } |
    { 'retailer' : null } |
    { 'online' : null },
  'inStock' : bigint,
  'subcategory' : string,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'category' : Category,
  'price' : bigint,
  'images' : Array<ExternalBlob>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createBlogPost' : ActorMethod<
    [string, string, string, string, ExternalBlob],
    undefined
  >,
  'createProduct' : ActorMethod<
    [
      string,
      string,
      string,
      Category,
      string,
      bigint,
      Array<ExternalBlob>,
      { 'both' : null } |
        { 'retailer' : null } |
        { 'online' : null },
      bigint,
    ],
    undefined
  >,
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBlogPostById' : ActorMethod<[string], [] | [BlogPost]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [CustomerProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getProductById' : ActorMethod<[string], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getProductsByCustomerType' : ActorMethod<
    [{ 'both' : null } | { 'retailer' : null } | { 'online' : null }],
    Array<Product>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [CustomerProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[string, ExternalBlob], string>,
  'removeFromCart' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[CustomerProfile], undefined>,
  'updateCartItemQuantity' : ActorMethod<[string, bigint], undefined>,
  'updateCustomerType' : ActorMethod<[CustomerType], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [
      string,
      string,
      string,
      Category,
      string,
      bigint,
      Array<ExternalBlob>,
      { 'both' : null } |
        { 'retailer' : null } |
        { 'online' : null },
      bigint,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];